### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Naveen-X** [AsmSafone/SafoneAPI#2]
File "/usr/local/lib/python3.9/site-packages/SafoneAPI/__init__.py", line 826, in translate
    return await self._fetch("translate", text=text, origin=origin, target=target)
  File "/usr/local/lib/python3.9/site-packages/SafoneAPI/__init__.py", line 68, in _fetch
    raise GenericApiError(
SafoneAPI.GenericApiError: Api Call Failed, Please report this: https://api.safone.tech/report

**Comment by AsmSafone** [comment]
> File "/usr/local/lib/python3.9/site-packages/SafoneAPI/**init**.py", line 826, in translate return await self._fetch("translate", text=text, origin=origin, target=target) File "/usr/local/lib/python3.9/site-packages/SafoneAPI/**init**.py", line 68, in _fetch raise GenericApiError( SafoneAPI.GenericApiError: Api Call Failed, Please report this: https://api.safone.tech/report

can you share reproducible example ?
